BEGIN;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS "IdempotencyRecords" (
    "Key" character varying(100) NOT NULL,
    "ResponseBody" text NOT NULL,
    "StatusCode" integer NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_IdempotencyRecords" PRIMARY KEY ("Key")
);

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "StudentId" character varying(50) NOT NULL,
    "Role" integer NOT NULL,
    "TelegramChatId" character varying(100),
    "DateOfBirth" timestamp with time zone,
    "EntryYear" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "TwoFactorCode" text,
    "TwoFactorExpiry" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Workshops" (
    "Id" uuid NOT NULL,
    "Title" character varying(300) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "SpeakerName" character varying(200) NOT NULL,
    "SpeakerBio" text NOT NULL,
    "Room" character varying(100) NOT NULL,
    "RoomMapUrl" text,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "TotalSlots" integer NOT NULL,
    "RegisteredCount" integer NOT NULL,
    "IsFree" boolean NOT NULL,
    "Price" decimal(10,2) NOT NULL,
    "Status" integer NOT NULL,
    "ImageUrl" text,
    "PdfUrl" text,
    "AiSummary" text,
    "AiSummaryGeneratedAt" timestamp with time zone,
    "CreatedByUserId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Workshops" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "SyncTasks" (
    "Id" uuid NOT NULL,
    "InputCsvUrl" text NOT NULL,
    "SuccessUrl" text,
    "ErrorUrl" text,
    "SyncState" integer NOT NULL,
    "ErrorMessage" text,
    "TotalRows" integer NOT NULL,
    "SuccessCount" integer NOT NULL,
    "ErrorCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    CONSTRAINT "PK_SyncTasks" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Registrations" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "WorkshopId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "QrCode" text,
    "QrToken" character varying(200),
    "IdempotencyKey" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Registrations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Registrations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Registrations_Workshops_WorkshopId" FOREIGN KEY ("WorkshopId") REFERENCES "Workshops" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Attendances" (
    "Id" uuid NOT NULL,
    "RegistrationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "WorkshopId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "CheckedInAt" timestamp with time zone NOT NULL,
    "IsSyncedFromOffline" boolean NOT NULL,
    "OfflineDeviceId" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attendances_Registrations_RegistrationId" FOREIGN KEY ("RegistrationId") REFERENCES "Registrations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Attendances_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Attendances_Workshops_WorkshopId" FOREIGN KEY ("WorkshopId") REFERENCES "Workshops" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Payments" (
    "Id" uuid NOT NULL,
    "RegistrationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Amount" decimal(10,2) NOT NULL,
    "Status" integer NOT NULL,
    "IdempotencyKey" character varying(100),
    "GatewayTransactionId" character varying(200),
    "GatewayResponse" text,
    "RetryCount" integer NOT NULL,
    "PaidAt" timestamp with time zone,
    "ExpiredAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Registrations_RegistrationId" FOREIGN KEY ("RegistrationId") REFERENCES "Registrations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_IdempotencyRecords_ExpiresAt" ON "IdempotencyRecords" ("ExpiresAt");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "Roles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "Users" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "Users" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "IX_Users_StudentId" ON "Users" ("StudentId");
CREATE INDEX IF NOT EXISTS "IX_Workshops_StartTime" ON "Workshops" ("StartTime");
CREATE INDEX IF NOT EXISTS "IX_Registrations_WorkshopId" ON "Registrations" ("WorkshopId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Registrations_UserId_WorkshopId" ON "Registrations" ("UserId", "WorkshopId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Attendances_RegistrationId" ON "Attendances" ("RegistrationId");
CREATE INDEX IF NOT EXISTS "IX_Attendances_WorkshopId" ON "Attendances" ("WorkshopId");
CREATE INDEX IF NOT EXISTS "IX_Attendances_UserId_WorkshopId" ON "Attendances" ("UserId", "WorkshopId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Payments_RegistrationId" ON "Payments" ("RegistrationId");
CREATE INDEX IF NOT EXISTS "IX_Payments_UserId" ON "Payments" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Payments_IdempotencyKey" ON "Payments" ("IdempotencyKey");
CREATE INDEX IF NOT EXISTS "IX_Payments_GatewayTransactionId" ON "Payments" ("GatewayTransactionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES
    ('20260426123039_InitialCreate', '10.0.7'),
    ('20260515115226_updb1', '10.0.7')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
